selectorWeight = 14
selectorThreshold = 700

[RBB1]
SMA_long = 1000
SMA_short = 50
#BULL
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60
#BEAR   
BEAR_RSI = 15
BEAR_RSI_high = 60
BEAR_RSI_low = 20
#ADX   
ADX = 3
ADX_high = 70
ADX_low = 50

[RBB2]
SMA_long = 1000
SMA_short = 50
#BULL
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60
#BEAR   
BEAR_RSI = 15
BEAR_RSI_high = 60
BEAR_RSI_low = 20
#ADX   
ADX = 3
ADX_high = 70
ADX_low = 50
